services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/data/stripe.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
