[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python init_db.py && gunicorn wsgi:app --config gunicorn.conf.py --log-level debug --capture-output --enable-stdio-inheritance --timeout 120 --workers 2 --preload --worker-class sync"
healthcheckPath = "/api/monitoring/health"
healthcheckTimeout = 600  # Increased timeout for initial database setup
healthcheckInterval = 60  # Increased interval
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
runtime = "python"
pythonVersion = "3.12"
packages = ["ffmpeg"]
