"""Add SearchUsage model and update schema

Revision ID: 849583a778c1
Revises: 
Create Date: 2025-01-26 00:36:48.415913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '849583a778c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('searches_used', sa.Integer(), nullable=True),
    sa.Column('searches_remaining', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_search_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('searches_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('searches_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_search_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['token'])
        batch_op.drop_column('success')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('search_query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_search_at')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('searches_remaining')
        batch_op.drop_column('searches_used')
        batch_op.drop_column('token')

    op.drop_table('search_usage')
    # ### end Alembic commands ###
